//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeLogDataApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeLogData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<double> StartMileage { get; set; }
        public Nullable<double> EndMileage { get; set; }
        public string Comment { get; set; }
        public string DriverName { get; set; }
        public string Division { get; set; }
        public string Campus { get; set; }
        public string Course { get; set; }
        public string VehicleRego { get; set; }
        public Nullable<double> Distance { get; set; }
        public string Status { get; set; }
        public string TripId { get; set; }
    }
}
